{"success":false,"exitStatus":1,"errorMessage":"Running band 0: 500.0 Hz to 1437.5 Hz\nError   : Could not read file 'horn.step'\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 229, in <module>\n    main()\n  File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 218, in main\n    run_simulation_from_step(\n  File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 114, in run_simulation_from_step\n    domain, facet_tags = create_mesh_from_step(step_file, mesh_size, horn_length)\n  File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 37, in create_mesh_from_step\n    gmsh.model.occ.importShapes(step_file)\n  File \"/usr/local/lib/gmsh.py\", line 8593, in importShapes\n    raise Exception(logger.getLastError())\nException: Could not read file 'horn.step'","errorReport":"Error executing process > 'run_simulation'\n\nCaused by:\n  Process `run_simulation` terminated with an error exit status (1)\n\n\nCommand executed:\n\n  echo \"Running band 0: 500.0 Hz to 1437.5 Hz\"\n  python3 -m horn_solver.solver         --step-file horn.step         --output-file results_0.csv         --min-freq 500.0         --max-freq 1437.5         --num-intervals 12         --length 0.5\n\nCommand exit status:\n  1\n\nCommand output:\n  Running band 0: 500.0 Hz to 1437.5 Hz\n\nCommand error:\n  Running band 0: 500.0 Hz to 1437.5 Hz\n  Error   : Could not read file 'horn.step'\n  Traceback (most recent call last):\n    File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 229, in <module>\n      main()\n    File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 218, in main\n      run_simulation_from_step(\n    File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 114, in run_simulation_from_step\n      domain, facet_tags = create_mesh_from_step(step_file, mesh_size, horn_length)\n    File \"/usr/local/lib/python3.10/dist-packages/horn_solver/solver.py\", line 37, in create_mesh_from_step\n      gmsh.model.occ.importShapes(step_file)\n    File \"/usr/local/lib/gmsh.py\", line 8593, in importShapes\n      raise Exception(logger.getLastError())\n  Exception: Could not read file 'horn.step'\n\nWork dir:\n  /Users/timrichardson/projects/horn/.nf-test/tests/80776d6d8becebe7895df51ca4f4191c/work/3b/c35c256d5d07932094e1c4e9e65925\n\nContainer:\n  horn-solver:latest\n\nTip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`"}